name = "howdy"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
description = "A simple webservice designed with an intuative API to try and take away a lot of the boilerplate in using a web server with Gleam"
repository = { type = "github", user = "mikeyjones", repo = "howdy" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.21"
cowboy = "~> 2.9"
gleam_cowboy = "~> 0.4"
gleam_erlang = "~> 0.9"
gleam_otp = "~> 0.4"
gleam_http = "~> 3.0"
gleam_json = "~> 0.4"
mimerl = "~> 1.2"

[dev-dependencies]
gleeunit = "~> 0.6"
