name = "howdy"
version = "0.1.2"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
description = "A simple and easy to use API created on top of the (Mist)[https://hex.pm/packages/mist] web server"
repository = { type = "github", user = "mikeyjones", repo = "howdy" }
links = [{ title = "Server", href = "https://github.com/mikeyjones/howdy/blob/main/manual/server.md" }, { title = "Router", href = "https://github.com/mikeyjones/howdy/blob/main/manual/routes.md" }, { title = "Context", href = "https://github.com/mikeyjones/howdy/blob/main/manual/context.md" }]

[dependencies]
gleam_stdlib = "~> 0.21"
gleam_erlang = "~> 0.9"
gleam_otp = "~> 0.4"
gleam_http = "~> 3.0"
gleam_json = "~> 0.4"
mimerl = "~> 1.2"
howdy_uuid = "~> 0.1"
mist = "~> 0.4"
gleam_hackney = "~> 0.2"

[dev-dependencies]
gleeunit = "~> 0.6"
