name = "howdy_auth_example"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.4.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_time = ">= 1.8.0 and < 2.0.0"
gleam_crypto = ">= 1.5.0 and < 2.0.0"
howdy = { path = "../.." }
gloo = ">= 1.0.2 and < 2.0.0"
howdy_auth = { path = "../../auth" }
howdy_database = { path = "../../database" }
simplifile = ">= 2.0.0 and < 3.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gsh = ">= 1.3.0 and < 2.0.0"

# The interactive console: see src/console.gleam.
[tools.gsh]
imports = ["console", "gleam/list", "gleam/option", "gleam/result"]
