//// Every page of the admin, driven through the app without a server,
//// against an in-memory SQLite database with auth installed.

import gleam/bool
import gleam/dynamic/decode
import gleam/erlang/process
import gleam/http/request
import gleam/list
import gleam/option.{Some}
import gleam/result
import gleam/string
import gleam/uri
import gleeunit
import gloo/adapter/sqlite
import gloo/migration as gloo_migration
import gloo/repo.{type Repo}
import gloo/sql
import howdy
import howdy/admin
import howdy/admin/internal/notify
import howdy/admin/internal/schema
import howdy/auth
import howdy/auth/group
import howdy/auth/secret
import howdy/auth/user
import howdy/authorization
import howdy/database
import howdy/database/postgres
import howdy/migration
import howdy/service
import howdy/testing

pub fn main() {
  gleeunit.main()
}

// -- Fixtures ----------------------------------------------------------------

fn notes() -> migration.Package {
  migration.Package("notes", [
    gloo_migration.new(
      1,
      "create",
      migration.per_database(
        postgres: "CREATE TABLE notes_notes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL, body TEXT, stars INTEGER NOT NULL DEFAULT 0)",
        sqlite: "CREATE TABLE notes_notes (id INTEGER PRIMARY KEY, title TEXT NOT NULL, body TEXT, stars INTEGER NOT NULL DEFAULT 0)",
      ),
    ),
  ])
}

@external(erlang, "howdy_admin_test_ffi", "getenv")
fn getenv(name: String) -> Result(String, Nil)

/// The whole suite runs on PostgreSQL instead when
/// HOWDY_ADMIN_TEST_POSTGRES_URL names a server whose database it may
/// empty; otherwise on an in-memory SQLite database.
fn with_database(run: fn(Repo) -> a) -> a {
  let db = case getenv("HOWDY_ADMIN_TEST_POSTGRES_URL") {
    Ok(url) -> {
      let assert Ok(config) = postgres.from_url(url)
      let assert Ok(db) = postgres.start(config)
      // Migrating auth from scratch for every test is slow enough to trip
      // eunit's timeout, so empty the tables instead once they exist.
      let assert Ok(installed) =
        repo.all(
          db,
          "SELECT tablename FROM pg_tables WHERE schemaname = current_schema() AND tablename NOT LIKE 'howdy_migration%'",
          [],
          decode.field(0, decode.string, decode.success),
        )
      let assert Ok(Nil) = case installed {
        [] -> Ok(Nil)
        tables -> {
          let assert Ok(Nil) = notify.uninstall(db)
          let assert Ok(_) = repo.execute(db, "DROP TABLE IF EXISTS loose", [])
          // Emptying auth's tables loses the default group it seeds.
          use _ <- result.try(
            database.execute(
              db,
              "TRUNCATE "
                <> string.join(
                list.map(
                  list.filter(tables, fn(t) { t != "loose" }),
                  schema.quote,
                ),
                ", ",
              )
                <> " RESTART IDENTITY CASCADE",
              [],
            ),
          )
          database.execute(
            db,
            "INSERT INTO howdy_auth_groups(id, name) VALUES ('default', 'Default')",
            [],
          )
        }
      }
      db
    }
    Error(Nil) -> {
      let assert Ok(db) = sqlite.start(sqlite.memory())
      let assert Ok(Nil) = database.sqlite_defaults(db)
      db
    }
  }
  let assert Ok(Nil) = migration.run(db, [auth.schema(), notes()])
  let value = run(db)
  let assert Ok(_) = repo.close(db)
  value
}

fn on_postgres(db: Repo) -> Bool {
  database.backend(db) == Ok(database.Postgres)
}

fn with_auth(run: fn(Repo, auth.Auth) -> a) -> a {
  use db <- with_database
  let assert Ok(identity) =
    auth.new_without_email(repo: db, origin: "http://localhost:8787")
  run(db, identity)
}

fn app(register: fn(admin.Admin) -> admin.Admin) -> howdy.App {
  howdy.new() |> admin.mount(admin.new() |> register)
}

fn get(app: howdy.App, path: String) -> String {
  let res =
    testing.get(path) |> request.set_host("localhost") |> testing.send(app)
  assert res.status == 200
    as { "GET " <> path <> " gave " <> string.inspect(res.status) }
  testing.text(res)
}

fn post(
  app: howdy.App,
  path: String,
  fields: List(#(String, String)),
) -> String {
  let res =
    testing.post_form(path, fields)
    |> request.set_host("localhost")
    |> testing.send(app)
  assert res.status == 303
    as {
      "POST "
      <> path
      <> " gave "
      <> string.inspect(res.status)
      <> ": "
      <> testing.text(res)
    }
  let assert Ok(location) = list.key_find(res.headers, "location")
  location
}

fn count(db: Repo, statement: String) -> Int {
  let assert Ok([n]) =
    repo.all(db, statement, [], decode.field(0, decode.int, decode.success))
  n
}

fn titles(db: Repo) -> List(String) {
  let assert Ok(rows) =
    repo.all(
      db,
      "SELECT title, body FROM notes_notes ORDER BY id",
      [],
      decode.field(0, decode.string, decode.success),
    )
  rows
}

// -- Mounting ----------------------------------------------------------------

pub fn overview_says_what_is_registered_test() {
  let bare = get(app(fn(a) { a }), "/_howdy")
  assert string.contains(bare, "Not registered")
  assert !string.contains(bare, "Browse tables")

  use db <- with_database
  let page = get(app(admin.database(_, db)), "/_howdy")
  assert string.contains(page, "SQLite") || string.contains(page, "PostgreSQL")
  assert string.contains(page, "Browse tables")
  assert string.contains(page, "auth v")
  assert string.contains(page, "notes v1")
  assert !string.contains(page, "Users")
}

pub fn auth_registers_its_database_too_test() {
  use _, identity <- with_auth
  let registered = admin.new() |> admin.auth(identity)
  assert admin.has_database(registered)
  assert admin.has_auth(registered)
  let page = get(app(fn(_) { registered }), "/_howdy")
  assert string.contains(page, "0 users")
  assert string.contains(page, "1 group")
  assert string.contains(page, "Browse tables")
}

pub fn mounts_at_another_prefix_test() {
  use db <- with_database
  let app = app(fn(a) { a |> admin.at("dev/admin/") |> admin.database(db) })
  assert string.contains(get(app, "/dev/admin"), "Browse tables")
  assert string.contains(get(app, "/dev/admin/data"), "notes_notes")
  let res =
    testing.get("/_howdy") |> request.set_host("localhost") |> testing.send(app)
  assert res.status == 404
}

pub fn refuses_other_hosts_test() {
  use db <- with_database
  let app = app(admin.database(_, db))
  let res =
    testing.get("/_howdy")
    |> request.set_host("evil.example")
    |> testing.send(app)
  assert res.status == 403
  let allowed =
    howdy.new()
    |> admin.mount(
      admin.new()
      |> admin.database(db)
      |> admin.allow_hosts(["dev.example.test"]),
    )
  let res =
    testing.get("/_howdy")
    |> request.set_host("dev.example.test")
    |> testing.send(allowed)
  assert res.status == 200
}

// -- Data --------------------------------------------------------------------

pub fn lists_tables_and_columns_test() {
  use db <- with_database
  let app = app(admin.database(_, db))
  // Howdy's own tables are hidden until asked for.
  let index = get(app, "/_howdy/data")
  assert string.contains(index, "notes_notes")
  assert !string.contains(index, "howdy_auth_users")
  assert string.contains(index, "Howdy tables too")
  let index = get(app, "/_howdy/data?all=1")
  assert string.contains(index, "notes_notes")
  assert string.contains(index, "howdy_auth_users")
  assert string.contains(index, "Hide Howdy")
  let table = get(app, "/_howdy/data/notes_notes")
  assert string.contains(table, "INTEGER") || string.contains(table, "integer")
  assert string.contains(table, "stars")
  assert string.contains(table, "/_howdy/live/data/notes_notes")
  let res =
    testing.get("/_howdy/data/nope")
    |> request.set_host("localhost")
    |> testing.send(app)
  assert res.status == 200
  assert string.contains(testing.text(res), "Not found")
}

pub fn inserts_edits_and_deletes_rows_test() {
  use db <- with_database
  let app = app(admin.database(_, db))
  // Empty columns take their defaults; NULL is explicit.
  let location =
    post(app, "/_howdy/data/notes_notes", [
      #("value-title", "First"),
      #("value-body", ""),
      #("null-body", "1"),
      #("value-stars", ""),
    ])
  assert location == "/_howdy/data/notes_notes"
  assert titles(db) == ["First"]
  assert count(
      db,
      "SELECT COUNT(*) FROM notes_notes WHERE body IS NULL AND stars = 0",
    )
    == 1

  let form = get(app, "/_howdy/data/notes_notes/row?k=1")
  assert string.contains(form, "value=\"First\"")
  let assert Ok(_) =
    repo.execute(db, "UPDATE notes_notes SET body = 'kept' WHERE id = 1", [])
  let _ =
    post(app, "/_howdy/data/notes_notes/row?k=1", [
      #("value-id", "1"),
      #("value-title", "Renamed"),
      #("value-body", "hello"),
      #("value-stars", "3"),
    ])
  assert titles(db) == ["Renamed"]
  assert count(
      db,
      "SELECT COUNT(*) FROM notes_notes WHERE body = 'hello' AND stars = 3",
    )
    == 1

  let _ = post(app, "/_howdy/data/notes_notes/row/delete?k=1", [])
  assert titles(db) == []
}

pub fn shows_the_database_error_when_a_write_is_refused_test() {
  use db <- with_database
  let app = app(admin.database(_, db))
  let res =
    testing.post_form("/_howdy/data/notes_notes", [#("value-body", "no title")])
    |> request.set_host("localhost")
    |> testing.send(app)
  assert res.status == 200
  assert string.contains(string.lowercase(testing.text(res)), "null")
  assert titles(db) == []
}

pub fn a_table_without_a_primary_key_is_addressed_by_rowid_test() {
  use db <- with_database
  use <- bool.guard(on_postgres(db), Nil)
  let assert Ok(_) = repo.execute(db, "CREATE TABLE loose (a TEXT, b TEXT)", [])
  let assert Ok(_) =
    repo.execute(db, "INSERT INTO loose VALUES ('x', 'y'), ('p', 'q')", [])
  let app = app(admin.database(_, db))
  let page = get(app, "/_howdy/data/loose/row?k=2")
  assert string.contains(page, "value=\"p\"")
  let _ =
    post(app, "/_howdy/data/loose/row?k=2", [
      #("value-a", "P"),
      #("value-b", "q"),
    ])
  assert count(db, "SELECT COUNT(*) FROM loose WHERE a = 'P'") == 1
  let _ = post(app, "/_howdy/data/loose/row/delete?k=1", [])
  assert count(db, "SELECT COUNT(*) FROM loose") == 1
}

pub fn a_postgres_table_without_a_primary_key_is_addressed_by_ctid_test() {
  use db <- with_database
  use <- bool.guard(!on_postgres(db), Nil)
  let assert Ok(_) = repo.execute(db, "CREATE TABLE loose (a TEXT, b TEXT)", [])
  let assert Ok(_) =
    repo.execute(db, "INSERT INTO loose VALUES ('x', 'y'), ('p', 'q')", [])
  let assert Ok([address]) =
    repo.all(
      db,
      "SELECT ctid::text FROM loose WHERE a = 'p'",
      [],
      decode.field(0, decode.string, decode.success),
    )
  let app = app(admin.database(_, db))
  let page =
    get(app, "/_howdy/data/loose/row?k=" <> uri.percent_encode(address))
  assert string.contains(page, "value=\"p\"")
  let _ =
    post(app, "/_howdy/data/loose/row?k=" <> uri.percent_encode(address), [
      #("value-a", "P"),
      #("value-b", "q"),
    ])
  assert count(db, "SELECT COUNT(*) FROM loose WHERE a = 'P'") == 1
}

// -- Notifications -----------------------------------------------------------

pub fn postgres_announces_changes_and_sqlite_does_not_test() {
  use db <- with_database
  let assert Ok(table) = schema.table(db, "notes_notes")
  case on_postgres(db) {
    False -> {
      assert !notify.available(db)
      assert notify.install(db, table) != Ok(Nil)
      assert notify.uninstall(db) == Ok(Nil)
    }
    True -> {
      assert notify.available(db)
      let assert Ok(Nil) = notify.install(db, table)
      // Installing twice leaves one trigger, and the package check still
      // passes with it there.
      let assert Ok(Nil) = notify.install(db, table)
      assert count(
          db,
          "SELECT COUNT(*) FROM pg_trigger WHERE tgname = 'howdy_admin_notify'",
        )
        == 1
      assert migration.check(db, notes()) == Ok(Nil)

      let heard = process.new_subject()
      let owner = process.spawn_unlinked(fn() { process.sleep(30_000) })
      let assert Ok(Nil) =
        notify.subscribe(db, owner, fn(name) { process.send(heard, name) })
      let assert Ok(_) =
        repo.execute(db, "INSERT INTO notes_notes (title) VALUES ('hello')", [])
      assert process.receive(heard, 5000) == Ok("notes_notes")
      let assert Ok(_) =
        repo.execute(db, "UPDATE notes_notes SET stars = 2", [])
      assert process.receive(heard, 5000) == Ok("notes_notes")

      // The listener follows its owner, and the triggers can be removed.
      process.kill(owner)
      process.sleep(200)
      let assert Ok(_) = repo.execute(db, "DELETE FROM notes_notes", [])
      assert process.receive(heard, 500) == Error(Nil)
      let assert Ok(Nil) = notify.uninstall(db)
      assert count(
          db,
          "SELECT COUNT(*) FROM pg_trigger WHERE tgname = 'howdy_admin_notify'",
        )
        == 0
    }
  }
}

// -- Auth --------------------------------------------------------------------

pub fn creates_lists_and_manages_users_test() {
  use db, identity <- with_auth
  let app = app(admin.auth(_, identity))
  assert string.contains(get(app, "/_howdy/users"), "No users yet")

  let location = post(app, "/_howdy/users", [#("email", "Ada@Example.com")])
  let assert "/_howdy/users/" <> id = location
  assert string.contains(get(app, "/_howdy/users"), "ada@example.com")
  let page = get(app, location)
  assert string.contains(page, "Sign in as this user")
  assert string.contains(page, "active")

  let _ = post(app, location <> "/suspend", [])
  let page = get(app, location)
  assert string.contains(page, "suspended")
  assert !string.contains(page, "Sign in as this user")
  let _ = post(app, location <> "/resume", [])
  assert string.contains(get(app, location), "active")
  let _ = post(app, location <> "/revoke", [])
  assert count(
      db,
      "SELECT COUNT(*) FROM howdy_auth_events WHERE action = 'sessions.revoked' AND client = 'howdy_admin'",
    )
    == 1
  let assert Ok(_) = auth.impersonate(identity, id, by: user.System)

  // A duplicate is refused with the reason on the page.
  let res =
    testing.post_form("/_howdy/users", [#("email", "ada@example.com")])
    |> request.set_host("localhost")
    |> testing.send(app)
  assert res.status == 200
  assert string.contains(testing.text(res), "already exists")
}

pub fn signing_in_as_a_user_sets_the_session_cookie_test() {
  use _, identity <- with_auth
  let app = app(admin.auth(_, identity))
  let assert "/_howdy/users/" <> id =
    post(app, "/_howdy/users", [#("email", "ada@example.com")])
  let res =
    testing.post_form("/_howdy/users/" <> id <> "/impersonate", [])
    |> request.set_host("localhost")
    |> testing.send(app)
  assert res.status == 303
  assert list.key_find(res.headers, "location") == Ok("/")
  let assert Ok(token) =
    list.key_find(testing.cookies(res), auth.cookie_name(identity))
  let assert Ok(principal) = auth.authenticate(identity, token)
  assert principal.user.id == id
}

pub fn manages_groups_test() {
  use db, identity <- with_auth
  let assert Ok(identity) = auth.with_groups(identity, group.OneGroupPerUser)
  let app = app(admin.auth(_, identity))
  let page = get(app, "/_howdy/groups")
  assert string.contains(page, "one-group-per-user")
  assert string.contains(page, "New group")

  let location =
    post(app, "/_howdy/groups", [#("name", "Acme"), #("id", "acme")])
  assert location == "/_howdy/groups/acme"
  let assert "/_howdy/groups/" <> generated =
    post(app, "/_howdy/groups", [#("name", "Generated"), #("id", "")])
  assert generated != ""
  let _ = post(app, location <> "/rename", [#("name", "Acme Ltd")])
  assert string.contains(get(app, location), "Acme Ltd")

  // A user created in a group, then moved to another.
  let assert "/_howdy/users/" <> id =
    post(app, "/_howdy/users", [
      #("email", "ada@example.com"),
      #("group", "acme"),
    ])
  assert string.contains(get(app, location), "ada@example.com")
  let _ = post(app, "/_howdy/users/" <> id <> "/move", [#("group", generated)])
  assert !string.contains(get(app, location), "ada@example.com")
  assert string.contains(
    get(app, "/_howdy/groups/" <> generated),
    "ada@example.com",
  )

  let _ = post(app, location <> "/delete", [])
  assert count(db, "SELECT COUNT(*) FROM howdy_auth_groups WHERE id = 'acme'")
    == 0
  let res =
    testing.post_form("/_howdy/groups/default/delete", [])
    |> request.set_host("localhost")
    |> testing.send(app)
  assert string.contains(testing.text(res), "default group cannot be deleted")
}

pub fn the_live_grid_serves_a_socket_route_test() {
  use db <- with_database
  let app = app(admin.database(_, db))
  // Without an upgrade request the socket route answers as a plain route
  // would: not a page, but not a routing miss either.
  let res =
    testing.get("/_howdy/live/data/notes_notes")
    |> request.set_host("localhost")
    |> testing.send(app)
  assert res.status != 404
  let _ = sql.string("unused")
}

// -- Authorization -----------------------------------------------------------

fn with_authorization(
  run: fn(Repo, auth.Auth, authorization.Authorization) -> a,
) -> a {
  let assert Ok(db) = sqlite.start(sqlite.memory())
  let assert Ok(Nil) = database.sqlite_defaults(db)
  let assert Ok(Nil) =
    migration.run(db, [auth.schema(), authorization.schema(), notes()])
  let assert Ok(identity) =
    auth.new_without_email(repo: db, origin: "http://localhost:8787")
  let assert Ok(access) = authorization.new(db)
  let value = run(db, identity, access)
  let assert Ok(_) = repo.close(db)
  value
}

pub fn roles_are_hidden_until_authorization_is_registered_test() {
  use _, identity, access <- with_authorization
  let without = get(app(admin.auth(_, identity)), "/_howdy")
  assert !string.contains(without, "/_howdy/roles")
  let registered =
    admin.new() |> admin.auth(identity) |> admin.authorization(access)
  assert admin.has_authorization(registered)
  let with = get(app(fn(_) { registered }), "/_howdy")
  assert string.contains(with, "0 roles")
  assert string.contains(with, "/_howdy/roles")
}

pub fn defines_lists_edits_and_deletes_roles_test() {
  use db, identity, access <- with_authorization
  let app =
    app(fn(a) { a |> admin.auth(identity) |> admin.authorization(access) })
  assert string.contains(get(app, "/_howdy/roles"), "No roles yet")

  let location =
    post(app, "/_howdy/roles", [
      #("name", "editor"),
      #("organization", "acme"),
      #("permissions", "invoices.read\ninvoices.write, invoices.read\n\n"),
    ])
  assert location == "/_howdy/roles/role?scope=org%3Aacme&name=editor"
  let _ =
    post(app, "/_howdy/roles", [#("name", "admin"), #("organization", "")])
  assert authorization.roles(access)
    == Ok([
      authorization.Role(authorization.Global, "admin", []),
      authorization.Role(authorization.Organization("acme"), "editor", [
        "invoices.read",
        "invoices.write",
      ]),
    ])
  let index = get(app, "/_howdy/roles")
  assert string.contains(index, "editor")
  assert string.contains(index, "org acme")
  assert string.contains(index, "invoices.write")

  let page = get(app, location)
  assert string.contains(page, "invoices.read\ninvoices.write")
  assert string.contains(page, "Nobody holds this role")
  let _ = post(app, location, [#("permissions", "invoices.read")])
  assert count(
      db,
      "SELECT COUNT(*) FROM howdy_authz_permissions WHERE role = 'editor'",
    )
    == 1

  let deleted =
    post(app, "/_howdy/roles/role/delete?scope=org%3Aacme&name=editor", [])
  assert deleted == "/_howdy/roles"
  assert count(db, "SELECT COUNT(*) FROM howdy_authz_roles") == 1

  // A missing or malformed role is reported, not crashed on.
  let res =
    testing.get("/_howdy/roles/role?scope=org%3A&name=editor")
    |> request.set_host("localhost")
    |> testing.send(app)
  assert string.contains(testing.text(res), "Not found")
  let res =
    testing.post_form("/_howdy/roles", [#("name", ""), #("organization", "")])
    |> request.set_host("localhost")
    |> testing.send(app)
  assert res.status == 200
  assert string.contains(testing.text(res), "nonempty")
}

pub fn assigns_and_revokes_roles_from_both_sides_test() {
  use _, identity, access <- with_authorization
  let app =
    app(fn(a) { a |> admin.auth(identity) |> admin.authorization(access) })
  let assert "/_howdy/users/" <> id =
    post(app, "/_howdy/users", [#("email", "ada@example.com")])
  let _ =
    post(app, "/_howdy/roles", [#("name", "admin"), #("organization", "")])
  let _ =
    post(app, "/_howdy/roles", [#("name", "editor"), #("organization", "acme")])
  let role = "/_howdy/roles/role?scope=global&name=admin"

  // From the role page: the user is offered, assigned, then listed.
  let page = get(app, role)
  assert string.contains(page, "ada@example.com")
  assert string.contains(page, "Nobody holds this role")
  let _ =
    post(app, "/_howdy/roles/role/assign?scope=global&name=admin", [
      #("user", id),
    ])
  assert authorization.assignments(access, id)
    == Ok([#(authorization.Global, "admin")])
  let page = get(app, role)
  assert !string.contains(page, "Nobody holds this role")
  assert string.contains(page, "Revoke")

  // From the user page: the held role shows, the other is offered.
  let page = get(app, "/_howdy/users/" <> id)
  assert string.contains(page, "global\tadmin")
  assert string.contains(page, "org:acme\teditor")
  let _ =
    post(app, "/_howdy/users/" <> id <> "/roles/assign", [
      #("role", "org:acme\teditor"),
    ])
  assert authorization.assignments(access, id)
    == Ok([
      #(authorization.Global, "admin"),
      #(authorization.Organization("acme"), "editor"),
    ])
  let _ =
    post(app, "/_howdy/users/" <> id <> "/roles/revoke", [
      #("role", "global\tadmin"),
    ])
  let _ =
    post(app, "/_howdy/roles/role/revoke?scope=org%3Aacme&name=editor", [
      #("user", id),
    ])
  assert authorization.assignments(access, id) == Ok([])

  let res =
    testing.post_form("/_howdy/users/" <> id <> "/roles/assign", [
      #("role", "nonsense"),
    ])
    |> request.set_host("localhost")
    |> testing.send(app)
  assert string.contains(testing.text(res), "choose a role")
}

// -- Sessions ----------------------------------------------------------------

pub fn lists_and_revokes_a_users_sessions_test() {
  use _, identity <- with_auth
  let app = app(admin.auth(_, identity))
  let assert "/_howdy/users/" <> id =
    post(app, "/_howdy/users", [#("email", "ada@example.com")])
  assert string.contains(
    get(app, "/_howdy/users/" <> id),
    "Not signed in anywhere",
  )

  let assert Ok(first) = auth.impersonate(identity, id, by: user.System)
  let assert Ok(second) = auth.impersonate(identity, id, by: user.System)
  let page = get(app, "/_howdy/users/" <> id)
  assert string.contains(page, "2 live sessions")
  assert string.contains(page, "impersonation")
  let assert Ok([newest, ..]) = auth.sessions_of(identity, id)

  let _ =
    post(app, "/_howdy/users/" <> id <> "/sessions/revoke", [
      #("session", newest.id),
    ])
  let assert Ok(remaining) = auth.sessions_of(identity, id)
  assert list.length(remaining) == 1
  // One of the two tokens still authenticates, the other does not.
  let alive =
    [first, second]
    |> list.filter(fn(session) {
      auth.authenticate(identity, secret.reveal(session.token)) |> result.is_ok
    })
  assert list.length(alive) == 1
  assert string.contains(get(app, "/_howdy/users/" <> id), "1 live session")
}

// -- Deletion ----------------------------------------------------------------

pub fn deletes_an_account_after_confirmation_test() {
  use db, identity <- with_auth
  // Without a cleanup callback the page says so and the route refuses.
  let before = app(admin.auth(_, identity))
  let assert "/_howdy/users/" <> id =
    post(before, "/_howdy/users", [#("email", "ada@example.com")])
  assert string.contains(
    get(before, "/_howdy/users/" <> id),
    "Account deletion is off",
  )
  let res =
    testing.post_form("/_howdy/users/" <> id <> "/delete", [
      #("confirm", "ada@example.com"),
    ])
    |> request.set_host("localhost")
    |> testing.send(before)
  assert string.contains(testing.text(res), "Forbidden")

  let identity =
    auth.with_account_deletion(identity, fn(conn, user) {
      repo.execute(conn, "DELETE FROM notes_notes WHERE title = $1", [
        sql.string(user.email),
      ])
      |> result.replace(Nil)
      |> result.replace_error(service.Internal("cleanup"))
    })
  let assert Ok(_) =
    repo.execute(
      db,
      "INSERT INTO notes_notes (title) VALUES ('ada@example.com')",
      [],
    )
  let after = app(admin.auth(_, identity))
  assert string.contains(get(after, "/_howdy/users/" <> id), "Delete account")

  // The wrong confirmation keeps the account.
  let res =
    testing.post_form("/_howdy/users/" <> id <> "/delete", [
      #("confirm", "grace@example.com"),
    ])
    |> request.set_host("localhost")
    |> testing.send(after)
  assert string.contains(testing.text(res), "to confirm")
  assert count(db, "SELECT COUNT(*) FROM howdy_auth_users") == 1

  let location =
    post(after, "/_howdy/users/" <> id <> "/delete", [
      #("confirm", " Ada@Example.com "),
    ])
  assert location == "/_howdy/users"
  assert count(db, "SELECT COUNT(*) FROM howdy_auth_users") == 0
  assert count(db, "SELECT COUNT(*) FROM notes_notes") == 0
  assert string.contains(get(after, "/_howdy/users"), "No users yet")
}

// -- Queries -----------------------------------------------------------------

fn seed_notes(db: Repo) -> Nil {
  list.each(
    [
      #("Apple pie", "sweet", 5),
      #("Banana bread", "sweet", 3),
      #("Chili", "hot", 4),
      #("Dal", "", 1),
    ],
    fn(note) {
      let assert Ok(_) =
        repo.execute(
          db,
          "INSERT INTO notes_notes (title, body, stars) VALUES ($1, $2, $3)",
          [sql.string(note.0), sql.string(note.1), sql.int(note.2)],
        )
      Nil
    },
  )
  let assert Ok(_) =
    repo.execute(
      db,
      "INSERT INTO notes_notes (title, stars) VALUES ('Eggs', 2)",
      [],
    )
  Nil
}

fn titles_of(rows: List(schema.Row)) -> List(String) {
  list.map(rows, fn(row) {
    let assert [_, Some(title), ..] = row.cells
    title
  })
}

pub fn searches_filters_sorts_and_pages_test() {
  use db <- with_database
  seed_notes(db)
  let assert Ok(table) = schema.table(db, "notes_notes")
  let base = schema.query()
  assert schema.count(db, table, base) == Ok(5)

  // Search is a case-insensitive substring match over every column, and
  // LIKE wildcards in the term are literal.
  let search = schema.Query(..base, search: "  AN  ")
  assert schema.count(db, table, search) == Ok(1)
  let assert Ok(rows) = schema.rows(db, table, search)
  assert titles_of(rows) == ["Banana bread"]
  assert schema.count(db, table, schema.Query(..base, search: "sweet")) == Ok(2)
  assert schema.count(db, table, schema.Query(..base, search: "%")) == Ok(0)

  // Filters combine with AND; comparisons respect the column's type.
  let hot =
    schema.Query(..base, filters: [schema.Filter("body", schema.Equals, "hot")])
  assert schema.count(db, table, hot) == Ok(1)
  let starry =
    schema.Query(..base, filters: [schema.Filter("stars", schema.Greater, "3")])
  let assert Ok(rows) = schema.rows(db, table, starry)
  assert titles_of(rows) == ["Apple pie", "Chili"]
  let both =
    schema.Query(..base, filters: [
      schema.Filter("stars", schema.Greater, "3"),
      schema.Filter("title", schema.Contains, "chi"),
    ])
  let assert Ok(rows) = schema.rows(db, table, both)
  assert titles_of(rows) == ["Chili"]
  let empty =
    schema.Query(..base, filters: [schema.Filter("body", schema.IsNull, "")])
  let assert Ok(rows) = schema.rows(db, table, empty)
  assert titles_of(rows) == ["Eggs"]
  let assert Ok(rows) =
    schema.rows(
      db,
      table,
      schema.Query(..base, filters: [
        schema.Filter("body", schema.NotNull, ""),
        schema.Filter("stars", schema.NotEquals, "5"),
        schema.Filter("stars", schema.Less, "4"),
      ]),
    )
  assert titles_of(rows) == ["Banana bread", "Dal"]
  // A filter on a column the table does not have is ignored, never
  // interpolated.
  let bogus =
    schema.Query(..base, filters: [
      schema.Filter("\" OR 1=1 --", schema.Equals, "x"),
    ])
  assert schema.count(db, table, bogus) == Ok(5)

  // Sorting, with the key as a tie-break, and an unknown column ignored.
  let assert Ok(rows) =
    schema.rows(
      db,
      table,
      schema.Query(..base, sort: Some(#("stars", schema.Descending))),
    )
  assert titles_of(rows)
    == ["Apple pie", "Chili", "Banana bread", "Eggs", "Dal"]
  let assert Ok(rows) =
    schema.rows(
      db,
      table,
      schema.Query(..base, sort: Some(#("nope", schema.Ascending))),
    )
  assert titles_of(rows)
    == ["Apple pie", "Banana bread", "Chili", "Dal", "Eggs"]

  // Pages.
  let assert Ok(rows) =
    schema.rows(db, table, schema.Query(..base, limit: 2, offset: 2))
  assert titles_of(rows) == ["Chili", "Dal"]
  let assert Ok(rows) =
    schema.rows(
      db,
      table,
      schema.Query(..base, search: "e", limit: 2, offset: 2),
    )
  assert list.length(rows) == 1
}
