import gleam/json
import gleam/list
import gleam/string
import howdy/ui/cli
import howdy/ui/registry
import simplifile

const root = "build/cli_test"

const dir = "build/cli_test/src/demo/ui"

fn reset() -> Nil {
  let _ = simplifile.delete(root)
  Nil
}

pub fn list_shows_every_entry_by_category_test() {
  let assert Ok(output) = cli.execute(["list"])
  use entry <- list.each(registry.entries())
  assert string.contains(output, "  " <> entry.name <> " ")
  assert string.contains(output, entry.category <> "\n")
  assert string.contains(output, "Buttons, and the theme toggle built on them.")
}

pub fn search_finds_by_description_and_category_test() {
  let assert Ok(output) = cli.execute(["search", "sign"])
  assert string.contains(output, "sign_in")
  assert string.contains(output, "sign_up")
  assert !string.contains(output, "button ")
  let assert Ok(output) = cli.execute(["search", "themes", "violet"])
  assert string.contains(output, "violet")
  let assert Ok(output) = cli.execute(["search", "zebra"])
  assert output == "nothing matches zebra"
}

pub fn view_shows_dependencies_and_source_test() {
  let assert Ok(output) = cli.execute(["view", "sign_in", "--to=" <> dir])
  assert string.contains(output, "sign_in (block, Blocks)")
  assert string.contains(output, "depends on: alert, button, card, checkbox")
  assert string.contains(output, "packages:   lustre, sketch")
  assert string.contains(output, "adds:       " <> dir <> "/sign_in.gleam")
  assert string.contains(output, "pub fn sign_in(")
}

pub fn add_copies_the_shipped_module_with_a_header_test() {
  reset()
  let assert Ok(output) = cli.execute(["add", "button", "--to=" <> dir])
  assert string.contains(output, "wrote " <> dir <> "/button.gleam")

  let assert Ok(copy) = simplifile.read(dir <> "/button.gleam")
  let assert Ok(shipped) = simplifile.read("src/howdy/ui/button.gleam")
  assert string.starts_with(
    copy,
    "//// Generated by howdy_ui " <> cli.version <> " from `howdy/ui/button`.",
  )
  assert string.ends_with(copy, shipped)
  // The copy only depends on the package's core modules, never on itself.
  assert string.contains(copy, "import howdy/ui/style.{class}")
  assert !string.contains(copy, "import howdy/ui\n")
}

pub fn add_brings_a_blocks_components_and_points_it_at_them_test() {
  reset()
  let assert Ok(output) = cli.execute(["add", "sign_in", "--to=" <> dir])
  // Dependencies first, then the block.
  use name <- list.each(["alert", "button", "card", "field", "input", "sign_in"])
  assert string.contains(output, "wrote " <> dir <> "/" <> name <> ".gleam")
  let assert Ok(block) = simplifile.read(dir <> "/sign_in.gleam")
  assert string.contains(block, "import demo/ui/button\n")
  assert string.contains(block, "import demo/ui/card\n")
  assert !string.contains(block, "import howdy/ui/button")
  // Core modules stay where they are.
  assert string.contains(block, "import howdy/ui/style.{class}")
  let assert Ok(index) = simplifile.read(dir <> "/all.gleam")
  assert string.contains(index, "sign_in.classes()")
  assert string.contains(index, "button.classes()")
}

pub fn add_keeps_an_edited_dependency_test() {
  reset()
  let assert Ok(_) = cli.execute(["add", "button", "--to=" <> dir])
  let path = dir <> "/button.gleam"
  let assert Ok(copy) = simplifile.read(path)
  let assert Ok(Nil) = simplifile.write(path, copy <> "\n// mine\n")
  let assert Ok(output) = cli.execute(["add", "stat_card", "--to=" <> dir])
  assert !string.contains(output, path <> " exists and differs; kept")
  let assert Ok(output) = cli.execute(["add", "sign_in", "--to=" <> dir])
  assert string.contains(
    output,
    path <> " exists and differs; kept your version",
  )
  let assert Ok(still) = simplifile.read(path)
  assert string.ends_with(still, "// mine\n")
}

pub fn dry_runs_change_nothing_test() {
  reset()
  let assert Ok(output) =
    cli.execute(["add", "sign_up", "--to=" <> dir, "--dry-run"])
  assert string.contains(output, "would write " <> dir <> "/select.gleam")
  assert string.contains(output, "would write " <> dir <> "/sign_up.gleam")
  assert simplifile.is_directory(dir) != Ok(True)
}

pub fn add_regenerates_the_all_module_test() {
  reset()
  let assert Ok(_) = cli.execute(["add", "layout", "button", "--to=" <> dir])
  let assert Ok(index) = simplifile.read(dir <> "/all.gleam")

  assert string.contains(
    index,
    "import demo/ui/button\nimport demo/ui/layout\n",
  )
  assert string.contains(
    index,
    "    button.classes(),\n    layout.classes(),\n",
  )

  // A hand-written module in the same directory joins in when it has a
  // `classes` function, and is ignored when it does not.
  let assert Ok(Nil) =
    simplifile.write(
      dir <> "/badge.gleam",
      "pub fn classes() -> List(Class) { [] }\n",
    )
  let assert Ok(Nil) =
    simplifile.write(dir <> "/helpers.gleam", "pub fn x() { 1 }\n")
  let assert Ok(_) = cli.execute(["add", "heading", "--to=" <> dir])
  let assert Ok(index) = simplifile.read(dir <> "/all.gleam")
  assert string.contains(index, "badge.classes()")
  assert string.contains(index, "heading.classes()")
  assert !string.contains(index, "helpers")
}

pub fn add_leaves_an_edited_copy_alone_and_shows_the_diff_test() {
  reset()
  let assert Ok(_) = cli.execute(["add", "heading", "--to=" <> dir])
  let path = dir <> "/heading.gleam"
  let assert Ok(copy) = simplifile.read(path)
  let edited = string.replace(copy, "\"2rem\"", "\"3rem\"")
  let assert Ok(Nil) = simplifile.write(path, edited)

  let assert Ok(output) = cli.execute(["add", "heading", "--to=" <> dir])
  assert string.contains(output, path <> " exists and differs")
  assert string.contains(output, "-  html.h1([class(heading_class(\"3rem\"))]")
  assert string.contains(output, "+  html.h1([class(heading_class(\"2rem\"))]")
  assert string.contains(
    output,
    "(generated by howdy_ui " <> cli.version <> ")",
  )
  let assert Ok(still) = simplifile.read(path)
  assert still == edited

  let assert Ok(output) =
    cli.execute(["add", "heading", "--to=" <> dir, "--force"])
  assert string.contains(output, "wrote " <> path)
  let assert Ok(restored) = simplifile.read(path)
  assert restored == copy
}

pub fn diff_reports_matching_missing_and_changed_copies_test() {
  reset()
  let assert Ok(_) = cli.execute(["add", "input", "--to=" <> dir])
  let assert Ok(output) =
    cli.execute(["diff", "input", "layout", "--to=" <> dir])
  assert string.contains(
    output,
    dir <> "/input.gleam matches howdy_ui " <> cli.version,
  )
  assert string.contains(output, dir <> "/layout.gleam does not exist")

  let path = dir <> "/input.gleam"
  let assert Ok(copy) = simplifile.read(path)
  let assert Ok(Nil) =
    simplifile.write(
      path,
      string.replace(
        copy,
        "css.display(\"block\"),\n    css.width",
        "css.width",
      ),
    )
  // Your copy is `---` and the shipped version is `+++`, so a line you
  // removed shows as one the package version adds.
  let assert Ok(output) = cli.execute(["diff", "input", "--to=" <> dir])
  assert string.contains(output, "--- " <> path)
  assert string.contains(output, "+    css.display(\"block\"),")
  assert string.contains(output, "...")
}

pub fn init_prepares_a_directory_and_a_theme_test() {
  reset()
  let assert Ok(output) = cli.execute(["init", "--to=" <> dir, "--theme=rose"])
  assert string.contains(output, "created " <> dir)
  assert string.contains(output, "wrote " <> dir <> "/rose.gleam")
  assert string.contains(output, "page.themes(demo/ui/rose.themes())")
  let assert Ok(theme) = simplifile.read(dir <> "/rose.gleam")
  assert string.contains(theme, "pub fn themes() -> Themes")
  let assert Ok(_) = simplifile.read(dir <> "/all.gleam")
}

pub fn a_published_registry_installs_like_the_built_in_one_test() {
  reset()
  let out = root <> "/registry"
  let assert Ok(output) = cli.execute(["registry", "--out=" <> out])
  assert string.contains(output, "index.json, llms.txt")
  let assert Ok(llms) = simplifile.read(out <> "/llms.txt")
  assert string.contains(llms, "# howdy_ui " <> cli.version)
  assert string.contains(llms, "- [button](button.json): ")

  // A registry of your own: an entry that depends on a built-in one.
  let own =
    cli.Item(
      name: "hello",
      kind: "block",
      category: "Mine",
      description: "Says hello.",
      module: "acme/hello",
      source: "//// Says hello.\n\nimport howdy/ui/button\n\npub fn classes() { [] }\n",
      dependencies: ["button"],
      packages: ["lustre"],
      origin: "",
    )
  let assert Ok(Nil) =
    simplifile.write(out <> "/hello.json", cli.item_json(own) |> json.to_string)
  let assert Ok(output) =
    cli.execute(["add", "hello", "--to=" <> dir, "--registry=" <> out])
  assert string.contains(output, "wrote " <> dir <> "/button.gleam")
  assert string.contains(output, "wrote " <> dir <> "/hello.gleam")
  let assert Ok(copy) = simplifile.read(dir <> "/hello.gleam")
  assert string.starts_with(
    copy,
    "//// Generated by " <> out <> " from `acme/hello`.",
  )
  assert string.contains(copy, "import demo/ui/button\n")

  let assert Ok(listed) = cli.execute(["list", "--registry=" <> out])
  assert string.contains(listed, "sign_in")
}

pub fn add_points_out_missing_direct_dependencies_test() {
  reset()
  // howdy_ui's own gleam.toml has lustre and sketch, so no hint here.
  let assert Ok(output) = cli.execute(["add", "button", "--to=" <> dir])
  assert !string.contains(output, "gleam add")
}

pub fn bad_input_is_explained_test() {
  let assert Error(message) = cli.execute(["add"])
  assert string.contains(message, "give at least one name")
  let assert Error(message) = cli.execute(["add", "modal", "--to=" <> dir])
  assert string.contains(message, "unknown name modal")
  let assert Error(message) = cli.execute(["add", "button", "--wat"])
  assert string.contains(message, "unknown option --wat")
  let assert Error(message) = cli.execute([])
  assert string.contains(message, "usage:")
  let assert Error(message) =
    cli.execute(["add", "x", "--to=" <> dir, "--registry=build/nowhere"])
  assert string.contains(message, "could not read build/nowhere/x.json")
}
