import gleam/list
import gleam/string
import howdy/ui/cli
import simplifile

const dir = "build/cli_test/src/demo/ui"

fn reset() -> Nil {
  let _ = simplifile.delete("build/cli_test")
  Nil
}

pub fn list_shows_every_component_with_a_summary_test() {
  let assert Ok(output) = cli.execute(["list"])
  use name <- list.each(cli.components)
  assert string.contains(output, name)
  assert string.contains(output, "Buttons, and the theme toggle built on them.")
}

pub fn add_copies_the_shipped_module_with_a_header_test() {
  reset()
  let assert Ok(output) = cli.execute(["add", "button", "--to=" <> dir])
  assert string.contains(output, "wrote " <> dir <> "/button.gleam")

  let assert Ok(copy) = simplifile.read(dir <> "/button.gleam")
  let assert Ok(shipped) = simplifile.read("src/howdy/ui/button.gleam")
  assert string.starts_with(
    copy,
    "//// Generated by howdy_ui " <> cli.version <> " from `howdy/ui/button`.",
  )
  assert string.ends_with(copy, shipped)
  // The copy only depends on the package's core modules, never on itself.
  assert string.contains(copy, "import howdy/ui/style.{class}")
  assert !string.contains(copy, "import howdy/ui\n")
}

pub fn add_regenerates_the_all_module_test() {
  reset()
  let assert Ok(_) = cli.execute(["add", "layout", "button", "--to=" <> dir])
  let assert Ok(index) = simplifile.read(dir <> "/all.gleam")

  assert string.contains(
    index,
    "import demo/ui/button\nimport demo/ui/layout\n",
  )
  assert string.contains(
    index,
    "    button.classes(),\n    layout.classes(),\n",
  )

  // A hand-written module in the same directory joins in when it has a
  // `classes` function, and is ignored when it does not.
  let assert Ok(Nil) =
    simplifile.write(
      dir <> "/badge.gleam",
      "pub fn classes() -> List(Class) { [] }\n",
    )
  let assert Ok(Nil) =
    simplifile.write(dir <> "/helpers.gleam", "pub fn x() { 1 }\n")
  let assert Ok(_) = cli.execute(["add", "heading", "--to=" <> dir])
  let assert Ok(index) = simplifile.read(dir <> "/all.gleam")
  assert string.contains(index, "badge.classes()")
  assert string.contains(index, "heading.classes()")
  assert !string.contains(index, "helpers")
}

pub fn add_leaves_an_edited_copy_alone_and_shows_the_diff_test() {
  reset()
  let assert Ok(_) = cli.execute(["add", "heading", "--to=" <> dir])
  let path = dir <> "/heading.gleam"
  let assert Ok(copy) = simplifile.read(path)
  let edited = string.replace(copy, "\"2rem\"", "\"3rem\"")
  let assert Ok(Nil) = simplifile.write(path, edited)

  let assert Ok(output) = cli.execute(["add", "heading", "--to=" <> dir])
  assert string.contains(output, path <> " exists and differs")
  assert string.contains(output, "-  html.h1([class(heading_class(\"3rem\"))]")
  assert string.contains(output, "+  html.h1([class(heading_class(\"2rem\"))]")
  assert string.contains(
    output,
    "(generated by howdy_ui " <> cli.version <> ")",
  )
  let assert Ok(still) = simplifile.read(path)
  assert still == edited

  let assert Ok(output) =
    cli.execute(["add", "heading", "--to=" <> dir, "--force"])
  assert string.contains(output, "wrote " <> path)
  let assert Ok(restored) = simplifile.read(path)
  assert restored == copy
}

pub fn diff_reports_matching_missing_and_changed_copies_test() {
  reset()
  let assert Ok(_) = cli.execute(["add", "input", "--to=" <> dir])
  let assert Ok(output) =
    cli.execute(["diff", "input", "layout", "--to=" <> dir])
  assert string.contains(
    output,
    dir <> "/input.gleam matches howdy_ui " <> cli.version,
  )
  assert string.contains(output, dir <> "/layout.gleam does not exist")

  let path = dir <> "/input.gleam"
  let assert Ok(copy) = simplifile.read(path)
  let assert Ok(Nil) =
    simplifile.write(
      path,
      string.replace(
        copy,
        "css.display(\"block\"),\n    css.width",
        "css.width",
      ),
    )
  // Your copy is `---` and the shipped version is `+++`, so a line you
  // removed shows as one the package version adds.
  let assert Ok(output) = cli.execute(["diff", "input", "--to=" <> dir])
  assert string.contains(output, "--- " <> path)
  assert string.contains(output, "+    css.display(\"block\"),")
  assert string.contains(output, "     css.width(percent(100)),")
  assert string.contains(output, "...")
}

pub fn add_points_out_missing_direct_dependencies_test() {
  reset()
  // howdy_ui's own gleam.toml has lustre and sketch, so no hint here.
  let assert Ok(output) = cli.execute(["add", "button", "--to=" <> dir])
  assert !string.contains(output, "gleam add")
}

pub fn bad_input_is_explained_test() {
  let assert Error(message) = cli.execute(["add"])
  assert string.contains(message, "give at least one component name")
  let assert Error(message) = cli.execute(["add", "modal"])
  assert string.contains(message, "unknown component modal")
  let assert Error(message) = cli.execute(["add", "button", "--wat"])
  assert string.contains(message, "unknown option --wat")
  let assert Error(message) = cli.execute([])
  assert string.contains(message, "usage:")
}
