//// Generated by howdy_ui 0.1.0. The classes of every
//// component in this directory, for `howdy/ui/export`. Regenerated
//// by `gleam run -m howdy/ui add`; do not edit.

import gleam/list
import howdy_live_example/ui/button
import sketch/css.{type Class}

pub fn classes() -> List(Class) {
  list.flatten([
    button.classes(),
  ])
}
